edit_uri: edit/master/docs/

extra:
    config_override: false
    doc_owner: Shashank Sharma
    doc_owner_shortid: ssharma06@verizonmedia.com
    social:
        - icon: fontawesome/regular/user-circle
          link: http://yo/u/shashank.sharma
          name: Shashank Sharma on Street
        - icon: fontawesome/brands/github
          link: https://git.vzbuilders.com/ssharma06/
          name: Shashank Sharma on Github
        - icon: fontawesome/brands/linkedin
          link: https://www.linkedin.com/in/shashank-sharma-932701108/
          name: Shashank Sharma on Linkedin
        - icon: fontawesome/brands/slack
          link: https://vzbuilders.slack.com/messages/@ssharma06
          name: Shashank Sharma on Slack
        - icon: fontawesome/brands/yahoo
          link: mailto://shashank.sharma@verizonmedia.com
          name: Mail Shashank Sharma
    data:
        git:
            schema_link: "https://git.vzbuilders.com/ssharma06/vzmi.ychaos/blob/master/vzmi/ychaos/testplan/resources/schema.json"
        general:
            todo: "This part of the documentation is under development. Stay tuned.."

extra_css: []

markdown_extensions:
    - admonition
    - codehilite
    - markdown_include.include:
        base_path: docs
    - toc:
        permalink: true
        toc_depth: 3
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_png
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
    - pymdownx.tabbed
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
    - YChaos:
        - Home: index.md
        - Changelog: changelog.md
        - Contribution: contribution.md
        - Project Dependencies: dependencies.md
    - YChaos Test Plan:
        - Test Plan: testplan/index.md
        - Schema: testplan/schema/index.html
    - Package Documentation:
        - testplan:
             - schema: package_docs/testplan/schema.md
             - verification: package_docs/testplan/verification.md
             - validator: package_docs/testplan/validator.md

plugins:
    - search
    - macros
    - mkdocstrings:
          watch:
              - vzmi/ychaos

remote_branch: gh-pages
remote_name: origin
repo_name: GitHub
repo_url: https://git.vzbuilders.com/ssharma06/vzmi.ychaos
site_name: YChaos - The Resilience Toolkit
site_url: https://git.vzbuilders.com/pages/ssharma06/vzmi.ychaos
site_description: Python module vzmi.ychaos
strict: false

theme:
    name: 'material'
    base_url: https://git.vzbuilders.com/ssharma06/vzmi.ychaos
    language: 'en'
    features:
        - navigation.tabs
    palette:
      primary: 'white'
    icon:
        repo: fontawesome/brands/github


use_directory_urls: true
